### ISSUE TITLE
Failed to add custom output config 

### ISSUE THREAD

**Issue by sureshamk** [kiwigrid/helm-charts#249] opened 2019-12-09 15:53 UTC
BUG REPORT

**Version of Helm and Kubernetes**:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"1da9875156ba0ad48e7d09a5d00e41489507f592", GitTreeState:"clean", BuildDate:"2019-11-14T05:19:20Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Helm 2

**What happened**:
Not able to update custom config for output

**What you expected to happen**:

Custom config should apply 
**How to reproduce it** (as minimally and precisely as possible):
`  elasticsearch:
    host: elk-elasticsearch-client
    port: 9200
    scheme: 'http'
    ssl_version: TLSv1_2
    buffer_chunk_limit: 1M
    buffer_queue_limit: 1
    logstash_prefix: 'logstash'
  configMaps:
    useDefaults:
      outputConf: false

  extraConfigMaps:
     output.conf: |-
       <filter kubernetes.**>
         @type kubernetes_metadata
       </filter>
       <match **>
         @type route
         remove_tag_prefix worker
         add_tag_prefix metrics.event

         <route **>
           copy
            @label @ERROR
         </route>
         <route **>
           copy
           @label @BACKUP
         </route>
       </match>
       <label @ERROR>
           <match **>
             @id elasticsearch
             @type elasticsearch
             @log_level info
             include_tag_key true
             type_name _doc
             host "#{ENV['OUTPUT_HOST']}"
             port "#{ENV['OUTPUT_PORT']}"
             scheme "#{ENV['OUTPUT_SCHEME']}"
             ssl_version "#{ENV['OUTPUT_SSL_VERSION']}"
             logstash_format true
             logstash_prefix "#{ENV['LOGSTASH_PREFIX']}"
             reconnect_on_error true
             <buffer>
               @type file
               path /var/log/fluentd-buffers/kubernetes.system.buffer
               flush_mode interval
               retry_type exponential_backoff
               flush_thread_count 2
               flush_interval 5s
               retry_forever
               retry_max_interval 30
               chunk_limit_size "#{ENV['OUTPUT_BUFFER_CHUNK_LIMIT']}"
               queue_limit_length "#{ENV['OUTPUT_BUFFER_QUEUE_LIMIT']}"
               overflow_action block
             </buffer>
           </match>
       </label>
       <label @BACKUP>
           <match **>
             @id elasticsearch
             @type elasticsearch
             @log_level info
             include_tag_key true
             type_name _doc
             host "#{ENV['OUTPUT_HOST']}"
             port "#{ENV['OUTPUT_PORT']}"
             scheme "#{ENV['OUTPUT_SCHEME']}"
             ssl_version "#{ENV['OUTPUT_SSL_VERSION']}"
             logstash_format true
             logstash_prefix "test"
             reconnect_on_error true
             <buffer>
               @type file
               path /var/log/fluentd-buffers/kubernetes.system.buffer
               flush_mode interval
               retry_type exponential_backoff
               flush_thread_count 2
               flush_interval 5s
               retry_forever
               retry_max_interval 30
               chunk_limit_size "#{ENV['OUTPUT_BUFFER_CHUNK_LIMIT']}"
               queue_limit_length "#{ENV['OUTPUT_BUFFER_QUEUE_LIMIT']}"
               overflow_action block
             </buffer>
           </match>
       </label>
`

**Anything else we need to know**:
I am trying to setup with stable/elastic-stack chart

Error from helm 

`helm  upgrade -i elk stable/elastic-stack --namespace logging --values values.yaml`
```
UPGRADE FAILED
Error: render error in "elastic-stack/charts/fluentd-elasticsearch/templates/daemonset.yaml": template: elastic-stack/charts/fluentd-elasticsearch/templates/daemonset.yaml:36:28: executing "elastic-stack/charts/fluentd-elasticsearch/templates/daemonset.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: elastic-stack/charts/fluentd-elasticsearch/templates/configmap.yaml:15:19: executing "elastic-stack/charts/fluentd-elasticsearch/templates/configmap.yaml" at <4>: wrong type for value; expected string; got map[string]interface {}
Error: UPGRADE FAILED: render error in "elastic-stack/charts/fluentd-elasticsearch/templates/daemonset.yaml": template: elastic-stack/charts/fluentd-elasticsearch/templates/daemonset.yaml:36:28: executing "elastic-stack/charts/fluentd-elasticsearch/templates/daemonset.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: elastic-stack/charts/fluentd-elasticsearch/templates/configmap.yaml:15:19: executing "elastic-stack/charts/fluentd-elasticsearch/templates/configmap.yaml" at <4>: wrong type for value; expected string; got map[string]interface {}
```

**Comment by monotek** [comment] 2019-12-09 16:06
I guess this is a duplicate of: https://github.com/kiwigrid/helm-charts/issues/122

At the moment it seems you can't use fluentd-elasticsearch in an umbrella chart. 
We're not planning to investigate in this as we're not using umbrella charts and also try to avoid them wherever possible, as updates can be a pain in the ass.

But if somebody would comes up with a solution we can implement in the chart we would gladly do.

**Closed by monotek** 2019-12-09 16:06 UTC
